site_name: Pomodoro Documentation
site_author: Gustavo Soares
site_url: https://GussSoares.github.io/pomodoro-cli

repo_url: https://github.com/GussSoares/pomodoro-cli
repo_name: GussSoares/pomodoro-cli
edit_uri: ""

# Copyright
copyright: |
  &copy; Gustavo Soares

theme:
  # icon:
  #   logo: material/clock
  logo: https://cdn-icons-png.flaticon.com/512/12238/12238205.png
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
  #   admonition:
  #     note: octicons/tag-16
  #     abstract: octicons/checklist-16
  #     info: octicons/info-16
  #     tip: octicons/squirrel-16
  #     success: octicons/check-16
  #     question: octicons/question-16
  #     warning: octicons/alert-16
  #     failure: octicons/x-circle-16
  #     danger: octicons/zap-16
  #     bug: octicons/bug-16
  #     example: octicons/beaker-16
  #     quote: octicons/quote-16

plugins:
  - mkdocstrings
  - search
  - git-revision-date
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: ./  # Set the base path to the root of your project
  - pymdownx.highlight:
      auto_title: true
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      linenums_style: pymdownx-inline
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - API Reference:
    - Pomodoro: api/pomodoro.md
    - Config: api/config.md
    - Constants: api/constants.md
    - Main: api/main.md